name: Publish Development Build
on:
    push:
        branches:
            - "1.21.1"

env:
  MINECRAFT_VERSION: "1.21.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: adopt
      - name: Build
        run: ./gradlew build
      - name: Get Fabric Jar Filename
        run: echo "NAME=jefff-mod-0.9.2-${{ env.MINECRAFT_VERSION }}" >> $GITHUB_ENV
      - name: Rename Output File
        run: mv ./build/libs/*.jar ./build/libs/${{ env.NAME }}.jar
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          makeLatest: true
          commit: 1.21.1
          tag: 0.9.2
          artifacts: |
            ./build/libs/*.jar
