
name: Publish Development Build
on:
    push:
        branches:
            - "1.21.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: adopt
      - name: Build
        run: ./gradlew build
      - name: Release
        uses: ncipollo/release-action@v1
        with:
#          automatic_release_tag: latest
          allowUpdates: true
          makeLatest: true
          commit: 1.21.1
          tag: 0.9.2
          artifacts: |
            ./build/libs/*.jar
